name: CI

on: push 

jobs:
  test:
    strategy:
      matrix:
        target: [test] # TODO: test-clj and test-cljs

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup CI Environment
        uses: yetanalytics/action-setup-env@v1

      - name: Run Tests
        run: make ${{ matrix.target }}
